import { Kunde, Berater } from "@/types";

// Echtes Team von CK IMMO FINANZ
export const team: Berater[] = [
  {
    id: "gf",
    name: "Christian Keller",
    email: "c.keller@ck-immofinanz.de",
    phone: "+49 170 1234567",
    role: "GF",
    aktiveFaelle: 8,
  },
  {
    id: "b1",
    name: "Sarah Weber",
    email: "s.weber@ck-immofinanz.de",
    phone: "+49 170 2345678",
    role: "BERATER",
    aktiveFaelle: 6,
  },
  {
    id: "b2",
    name: "Michael Schmidt",
    email: "m.schmidt@ck-immofinanz.de",
    phone: "+49 170 3456789",
    role: "BERATER",
    aktiveFaelle: 5,
  },
  {
    id: "b3",
    name: "Anna Müller",
    email: "a.mueller@ck-immofinanz.de",
    phone: "+49 170 4567890",
    role: "BERATER",
    aktiveFaelle: 4,
  },
  {
    id: "b4",
    name: "Thomas Fischer",
    email: "t.fischer@ck-immofinanz.de",
    phone: "+49 170 5678901",
    role: "BERATER",
    aktiveFaelle: 3,
  },
  {
    id: "az",
    name: "Eray",
    email: "eray@ck-immofinanz.de",
    phone: "+49 170 6789012",
    role: "AZUBI",
    aktiveFaelle: 2,
  },
  {
    id: "ah",
    name: "Oguzhan",
    email: "oguzhan@ck-immofinanz.de",
    phone: "+49 170 7890123",
    role: "AUSHILFE",
    aktiveFaelle: 1,
  },
];

// Realistische Demo-Kunden
export const kunden: Kunde[] = [
  {
    id: "k1",
    name: "Thomas Müller",
    email: "t.mueller@email.de",
    phone: "+49 171 1111111",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 450000,
    objektadresse: "Gartenweg 8, 80992 München",
    phase: 5,
    status: "green",
    tageInPhase: 2,
    letzterKontakt: "2024-12-10",
    naechsteAktion: "Finanzierungskonzept vorstellen",
    fehlendeDokumente: [],
    beraterId: "gf",
    erstelltAm: "2024-11-15",
  },
  {
    id: "k2",
    name: "Anna Schmidt",
    email: "a.schmidt@email.de",
    phone: "+49 171 2222222",
    objectType: "NEUBAU",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 620000,
    objektadresse: "Neubaugebiet West, Frankfurt",
    phase: 3,
    status: "yellow",
    tageInPhase: 5,
    letzterKontakt: "2024-12-08",
    naechsteAktion: "Fehlende Unterlagen nachfordern",
    fehlendeDokumente: ["Gehaltsnachweise (3 Monate)", "Kontoauszüge"],
    beraterId: "b1",
    erstelltAm: "2024-11-20",
  },
  {
    id: "k3",
    name: "Michael Weber",
    email: "m.weber@email.de",
    phone: "+49 171 3333333",
    objectType: "KAPITALANLAGE",
    employmentType: "SELBSTSTAENDIG",
    finanzierungsvolumen: 890000,
    objektadresse: "MFH Südstadt, Köln",
    phase: 6,
    status: "red",
    tageInPhase: 4,
    letzterKontakt: "2024-12-09",
    naechsteAktion: "DRINGEND: Angebot läuft ab",
    fehlendeDokumente: [],
    beraterId: "gf",
    erstelltAm: "2024-10-28",
  },
  {
    id: "k4",
    name: "Julia Becker",
    email: "j.becker@email.de",
    phone: "+49 171 4444444",
    objectType: "EIGENNUTZER",
    employmentType: "BEAMTET",
    finanzierungsvolumen: 380000,
    objektadresse: "Reihenhaus, Stuttgart-Süd",
    phase: 8,
    status: "green",
    tageInPhase: 1,
    letzterKontakt: "2024-12-11",
    naechsteAktion: "Auf Bankrückmeldung warten",
    fehlendeDokumente: [],
    beraterId: "b2",
    erstelltAm: "2024-09-15",
  },
  {
    id: "k5",
    name: "Stefan Hoffmann",
    email: "s.hoffmann@email.de",
    phone: "+49 171 5555555",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 520000,
    objektadresse: "Altbauwohnung, Düsseldorf",
    phase: 9,
    status: "green",
    tageInPhase: 0,
    letzterKontakt: "2024-12-12",
    naechsteAktion: "Kreditvertrag vorbereiten",
    fehlendeDokumente: [],
    beraterId: "b1",
    erstelltAm: "2024-08-20",
  },
  {
    id: "k6",
    name: "Laura Fischer",
    email: "l.fischer@email.de",
    phone: "+49 171 6666666",
    objectType: "NEUBAU",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 710000,
    objektadresse: "HafenCity, Hamburg",
    phase: 2,
    status: "green",
    tageInPhase: 1,
    letzterKontakt: "2024-12-11",
    naechsteAktion: "Erstgespräch führen",
    fehlendeDokumente: [],
    beraterId: "gf",
    erstelltAm: "2024-12-10",
  },
  {
    id: "k7",
    name: "Markus Klein",
    email: "m.klein@email.de",
    phone: "+49 171 7777777",
    objectType: "GEWERBE",
    employmentType: "SELBSTSTAENDIG",
    finanzierungsvolumen: 1250000,
    objektadresse: "Gewerbeobjekt, Nürnberg",
    phase: 4,
    status: "yellow",
    tageInPhase: 3,
    letzterKontakt: "2024-12-09",
    naechsteAktion: "Selbstauskunft nachfassen",
    fehlendeDokumente: ["BWA (aktuell)", "Steuerbescheide"],
    beraterId: "b3",
    erstelltAm: "2024-11-01",
  },
  {
    id: "k8",
    name: "Sandra Braun",
    email: "s.braun@email.de",
    phone: "+49 171 8888888",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 280000,
    objektadresse: "ETW Leipzig-Zentrum",
    phase: 1,
    status: "green",
    tageInPhase: 0,
    letzterKontakt: "2024-12-12",
    naechsteAktion: "Erstkontakt herstellen",
    fehlendeDokumente: [],
    beraterId: "b1",
    erstelltAm: "2024-12-12",
  },
  {
    id: "k9",
    name: "Peter Wagner",
    email: "p.wagner@email.de",
    phone: "+49 171 9999999",
    objectType: "KAPITALANLAGE",
    employmentType: "RENTNER",
    finanzierungsvolumen: 350000,
    objektadresse: "MFH Dresden-Neustadt",
    phase: 10,
    status: "green",
    tageInPhase: 2,
    letzterKontakt: "2024-12-10",
    naechsteAktion: "Notartermin am 18.12.",
    fehlendeDokumente: [],
    beraterId: "gf",
    erstelltAm: "2024-07-10",
  },
  {
    id: "k10",
    name: "Nicole Zimmermann",
    email: "n.zimmermann@email.de",
    phone: "+49 171 1010101",
    objectType: "NEUBAU",
    employmentType: "SELBSTSTAENDIG",
    finanzierungsvolumen: 950000,
    objektadresse: "Penthouse, Düsseldorf",
    phase: 3,
    status: "red",
    tageInPhase: 6,
    letzterKontakt: "2024-12-06",
    naechsteAktion: "STAU: Kunde kontaktieren",
    fehlendeDokumente: ["BWA", "Steuerbescheide", "Kontoauszüge"],
    beraterId: "gf",
    erstelltAm: "2024-11-25",
  },
  {
    id: "k11",
    name: "Robert Schulz",
    email: "r.schulz@email.de",
    phone: "+49 171 1111222",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 330000,
    objektadresse: "ETW Bremen-Mitte",
    phase: 11,
    status: "green",
    tageInPhase: 14,
    letzterKontakt: "2024-11-28",
    naechsteAktion: "Google-Bewertung anfragen",
    fehlendeDokumente: [],
    beraterId: "b2",
    erstelltAm: "2024-05-12",
  },
  {
    id: "k12",
    name: "Christina Lange",
    email: "c.lange@email.de",
    phone: "+49 171 1212121",
    objectType: "EIGENNUTZER",
    employmentType: "ANGESTELLT",
    finanzierungsvolumen: 420000,
    objektadresse: "DHH Hannover-Süd",
    phase: 7,
    status: "green",
    tageInPhase: 4,
    letzterKontakt: "2024-12-08",
    naechsteAktion: "Auf Objektzusage warten",
    fehlendeDokumente: [],
    beraterId: "b4",
    erstelltAm: "2024-09-25",
  },
];

// KPIs berechnen (aus Anforderungsdokument)
export function getKPIs() {
  const pipelineWert = kunden.reduce((s, k) => s + k.finanzierungsvolumen, 0);
  const aktiveFaelle = kunden.filter((k) => k.phase < 11).length;
  const kritischeFaelle = kunden.filter((k) => k.status === "red").length;
  const warnungen = kunden.filter((k) => k.status === "yellow").length;
  const neueLeads = kunden.filter((k) => k.phase === 1).length;
  const abschluesse = kunden.filter((k) => k.phase >= 10).length;
  const stauFaelle = kunden.filter((k) => k.tageInPhase >= 3 && k.phase < 10).length;

  // Durchlaufzeit Phase 1-3 (Durchschnitt Tage)
  const phase1bis3 = kunden.filter((k) => k.phase <= 3);
  const durchlaufzeit = phase1bis3.length > 0
    ? Math.round(phase1bis3.reduce((s, k) => s + k.tageInPhase, 0) / phase1bis3.length)
    : 0;

  return {
    pipelineWert,
    aktiveFaelle,
    kritischeFaelle,
    warnungen,
    neueLeads,
    abschluesse,
    stauFaelle,
    durchlaufzeit,
  };
}

export function getBeraterById(id: string): Berater | undefined {
  return team.find((b) => b.id === id);
}

export function getKundenByPhase(phase: number): Kunde[] {
  return kunden.filter((k) => k.phase === phase);
}

export function getKundenByBerater(beraterId: string): Kunde[] {
  return kunden.filter((k) => k.beraterId === beraterId);
}
