import { Kunde, Berater } from "@/types";

export const demoBerater: Berater[] = [
  {
    id: "1",
    name: "Christian Keller",
    email: "c.keller@ck-immofinanz.de",
    phone: "+49 170 1234567",
    role: "GF",
    kundenCount: 12,
  },
  {
    id: "2",
    name: "Sarah Schmidt",
    email: "s.schmidt@ck-immofinanz.de",
    phone: "+49 170 2345678",
    role: "BERATER",
    kundenCount: 8,
  },
  {
    id: "3",
    name: "Max Weber",
    email: "m.weber@ck-immofinanz.de",
    phone: "+49 170 3456789",
    role: "BERATER",
    kundenCount: 6,
  },
];

export const demoKunden: Kunde[] = [
  {
    id: "1",
    name: "Thomas Müller",
    email: "t.mueller@email.de",
    phone: "+49 171 1111111",
    address: "Hauptstraße 15, 80331 München",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    financingVolume: 45000000,
    propertyAddress: "Gartenweg 8, 80992 München",
    phase: 5,
    status: "ok",
    daysInPhase: 2,
    lastContactAt: "2024-12-10T14:30:00Z",
    autoFollowUp: true,
    nextAction: "Finanzierungskonzept vorstellen",
    deadlineDays: 3,
    berater: demoBerater[0],
    missingDocs: [],
    createdAt: "2024-11-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Anna Schmidt",
    email: "a.schmidt@email.de",
    phone: "+49 171 2222222",
    address: "Bahnhofstr. 42, 60329 Frankfurt",
    objectType: "NEUBAU",
    employmentType: "ANGESTELLT",
    financingVolume: 62000000,
    propertyAddress: "Neubaugebiet West, 60437 Frankfurt",
    phase: 3,
    status: "warning",
    statusText: "Unterlagen unvollständig",
    daysInPhase: 5,
    lastContactAt: "2024-12-08T09:15:00Z",
    autoFollowUp: true,
    nextAction: "Fehlende Unterlagen nachfordern",
    deadlineDays: 1,
    berater: demoBerater[1],
    missingDocs: ["Gehaltsnachweise (3 Monate)", "Kontoauszüge"],
    createdAt: "2024-11-20T11:30:00Z",
  },
  {
    id: "3",
    name: "Michael Weber",
    email: "m.weber@email.de",
    phone: "+49 171 3333333",
    address: "Lindenallee 7, 50667 Köln",
    objectType: "KAPITALANLAGE",
    employmentType: "SELBSTSTAENDIG",
    financingVolume: 89000000,
    propertyAddress: "Mehrfamilienhaus, Südstadt Köln",
    phase: 6,
    status: "critical",
    statusText: "Angebot läuft in 1 Tag ab!",
    daysInPhase: 4,
    lastContactAt: "2024-12-09T16:45:00Z",
    autoFollowUp: true,
    nextAction: "Dringend: Angebot besprechen",
    deadlineDays: 1,
    berater: demoBerater[0],
    missingDocs: [],
    createdAt: "2024-10-28T08:00:00Z",
  },
  {
    id: "4",
    name: "Julia Becker",
    email: "j.becker@email.de",
    phone: "+49 171 4444444",
    address: "Schlossstr. 23, 70173 Stuttgart",
    objectType: "EIGENNUTZER",
    employmentType: "BEAMTET",
    financingVolume: 38000000,
    propertyAddress: "Reihenhaus, 70567 Stuttgart",
    phase: 8,
    status: "ok",
    daysInPhase: 1,
    lastContactAt: "2024-12-11T10:00:00Z",
    autoFollowUp: true,
    nextAction: "Auf Bankrückmeldung warten",
    deadlineDays: 7,
    berater: demoBerater[2],
    missingDocs: [],
    createdAt: "2024-09-15T14:20:00Z",
  },
  {
    id: "5",
    name: "Stefan Hoffmann",
    email: "s.hoffmann@email.de",
    phone: "+49 171 5555555",
    address: "Marktplatz 3, 40213 Düsseldorf",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    financingVolume: 52000000,
    propertyAddress: "Altbauwohnung, 40215 Düsseldorf",
    phase: 9,
    status: "ok",
    statusText: "Kreditzusage erhalten!",
    daysInPhase: 0,
    lastContactAt: "2024-12-12T08:30:00Z",
    autoFollowUp: true,
    nextAction: "Kreditvertrag vorbereiten",
    deadlineDays: 5,
    berater: demoBerater[1],
    missingDocs: [],
    createdAt: "2024-08-20T09:00:00Z",
  },
  {
    id: "6",
    name: "Laura Fischer",
    email: "l.fischer@email.de",
    phone: "+49 171 6666666",
    address: "Bergweg 11, 20095 Hamburg",
    objectType: "NEUBAU",
    employmentType: "ANGESTELLT",
    financingVolume: 71000000,
    propertyAddress: "Neubauprojekt HafenCity",
    phase: 2,
    status: "ok",
    daysInPhase: 1,
    lastContactAt: "2024-12-11T15:00:00Z",
    autoFollowUp: true,
    nextAction: "Erstgespräch führen",
    deadlineDays: 2,
    berater: demoBerater[0],
    missingDocs: [],
    createdAt: "2024-12-10T12:00:00Z",
  },
  {
    id: "7",
    name: "Markus Klein",
    email: "m.klein@email.de",
    phone: "+49 171 7777777",
    address: "Industriestr. 45, 90402 Nürnberg",
    objectType: "GEWERBE",
    employmentType: "SELBSTSTAENDIG",
    financingVolume: 125000000,
    propertyAddress: "Gewerbeobjekt, Nürnberg Nord",
    phase: 4,
    status: "warning",
    statusText: "Selbstauskunft ausstehend",
    daysInPhase: 3,
    lastContactAt: "2024-12-09T11:30:00Z",
    autoFollowUp: true,
    nextAction: "Selbstauskunft nachfassen",
    deadlineDays: 2,
    berater: demoBerater[2],
    missingDocs: ["BWA", "Steuerbescheide"],
    createdAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "8",
    name: "Sandra Braun",
    email: "s.braun@email.de",
    phone: "+49 171 8888888",
    address: "Parkstr. 9, 04109 Leipzig",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    financingVolume: 28000000,
    propertyAddress: "ETW, Leipzig Zentrum",
    phase: 1,
    status: "ok",
    daysInPhase: 0,
    lastContactAt: "2024-12-12T09:00:00Z",
    autoFollowUp: true,
    nextAction: "Willkommens-WhatsApp senden",
    berater: demoBerater[1],
    missingDocs: [],
    createdAt: "2024-12-12T09:00:00Z",
  },
  {
    id: "9",
    name: "Peter Wagner",
    email: "p.wagner@email.de",
    phone: "+49 171 9999999",
    address: "Alte Gasse 17, 01067 Dresden",
    objectType: "KAPITALANLAGE",
    employmentType: "RENTNER",
    financingVolume: 35000000,
    propertyAddress: "MFH Dresden Neustadt",
    phase: 10,
    status: "ok",
    statusText: "Notartermin am 18.12.",
    daysInPhase: 2,
    lastContactAt: "2024-12-10T14:00:00Z",
    autoFollowUp: true,
    nextAction: "Notartermin vorbereiten",
    deadlineDays: 6,
    berater: demoBerater[0],
    missingDocs: [],
    createdAt: "2024-07-10T08:00:00Z",
  },
  {
    id: "10",
    name: "Christina Lange",
    email: "c.lange@email.de",
    phone: "+49 171 1010101",
    address: "Seestr. 28, 30159 Hannover",
    objectType: "EIGENNUTZER",
    employmentType: "ANGESTELLT",
    financingVolume: 42000000,
    propertyAddress: "DHH, Hannover Süd",
    phase: 7,
    status: "ok",
    daysInPhase: 4,
    lastContactAt: "2024-12-08T13:00:00Z",
    autoFollowUp: true,
    nextAction: "Auf Objektzusage warten",
    deadlineDays: 10,
    berater: demoBerater[2],
    missingDocs: [],
    createdAt: "2024-09-25T11:00:00Z",
  },
  {
    id: "11",
    name: "Robert Schulz",
    email: "r.schulz@email.de",
    phone: "+49 171 1111222",
    address: "Wiesenweg 5, 28195 Bremen",
    objectType: "BESTAND",
    employmentType: "ANGESTELLT",
    financingVolume: 33000000,
    propertyAddress: "ETW Bremen Mitte",
    phase: 11,
    status: "ok",
    statusText: "Abgeschlossen - Nachbetreuung",
    daysInPhase: 14,
    lastContactAt: "2024-11-28T10:00:00Z",
    autoFollowUp: false,
    nextAction: "Google-Bewertung anfragen",
    berater: demoBerater[1],
    missingDocs: [],
    createdAt: "2024-05-12T09:00:00Z",
  },
  {
    id: "12",
    name: "Nicole Zimmermann",
    email: "n.zimmermann@email.de",
    phone: "+49 171 1212121",
    address: "Königsallee 100, 40212 Düsseldorf",
    objectType: "NEUBAU",
    employmentType: "SELBSTSTAENDIG",
    financingVolume: 95000000,
    propertyAddress: "Penthouse, Düsseldorf Oberkassel",
    phase: 3,
    status: "critical",
    statusText: "Seit 6 Tagen keine Aktivität!",
    daysInPhase: 6,
    lastContactAt: "2024-12-06T16:00:00Z",
    autoFollowUp: true,
    nextAction: "DRINGEND: Kunde kontaktieren",
    deadlineDays: 0,
    berater: demoBerater[0],
    missingDocs: ["BWA", "Steuerbescheide", "Kontoauszüge"],
    createdAt: "2024-11-25T14:00:00Z",
  },
];

export function getKPIs() {
  const totalVolume = demoKunden.reduce((sum, k) => sum + k.financingVolume, 0);
  const criticalCount = demoKunden.filter((k) => k.status === "critical").length;
  const warningCount = demoKunden.filter((k) => k.status === "warning").length;
  const newLeads = demoKunden.filter((k) => k.phase === 1).length;
  const closedThisMonth = demoKunden.filter((k) => k.phase >= 10).length;

  return {
    totalVolume,
    totalKunden: demoKunden.length,
    criticalCount,
    warningCount,
    newLeads,
    closedThisMonth,
  };
}

export function getKundenByPhase(phase: number): Kunde[] {
  return demoKunden.filter((k) => k.phase === phase);
}

export function getKundenByBerater(beraterId: string): Kunde[] {
  return demoKunden.filter((k) => k.berater?.id === beraterId);
}
